{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: actual-sync
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .config.yml: |
{{ .Values.config.data | indent 4 }}
{{- end }}