apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: actual-sync
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: actual-sync
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-configmap-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: actual-sync
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-configmap-reader
  apiGroup: rbac.authorization.k8s.io